Creating virtual display

Getting report sources

Loading target  http://hamiltonoh.policereports.us/

None
Failed to load target
Parsing target for last update string
Detecting if more than one <center></center>

Page was last updated on Last Report Upload: March 7, 2016, 10:56 am

Performing a full 30 day scan on  http://hamiltonoh.policereports.us/
Preparing old reports for comparison

Iterating through daterange
Submitting search for  03/07/16
Submitting search for  03/06/16

Downloading report_2016-036994.pdf
From http://hamiltonoh.policereports.us/viewreportpdfraw.html?sid=khoualj3j0tg5rk3sfjpf75d85&rid=0&f=report.pdf

Closing browser

Traceback (most recent call last):
  File "../maindev.py", line 202, in <module>
    main()
  File "../maindev.py", line 82, in main
    searchResults = s.check_police_reports_us(source, title, link)
  File "/srv/service/grabreports/modules/search.py", line 381, in check_police_reports_us
    updateResults = self.scan_police_reports_us(source, county, target)
  File "/srv/service/grabreports/modules/search.py", line 499, in scan_police_reports_us
    link = d.single_police_reports_us(target, reportNumber, sid, rid, date, pFunction)
  File "/srv/service/grabreports/modules/download.py", line 240, in single_police_reports_us
    thePdf = urllib2.urlopen(pdfLink)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
